### ISSUE TITLE
PHP8 seems to make troubles

### ISSUE THREAD

**Issue by hobbycodersince1990** [42coders/workflows#5]
The installed Versions:
Development Environment: Windows 10, latest
Composer version 2.0.11
PHP 8.0.3
Laravel Framework 8.33.1

The composer commands I needed to start with parameter --ignore-platform-reqs in order to ignore the 7.x requirement.

Then I'm using the "php artisan serve" to run on my local environment.
And the latest Chrome Browser to start http://localhost:8000/workflows

Now I follow your video Tutorial. When I want to configure the HTML input, the dialog is not opening.

**Comment by hobbycodersince1990** [comment]
Same situation on Ubuntu Linux with PHP 7.4.3 and Apache.

Apache settings:
```
<VirtualHost *:80>
    ServerName server.mydomain.com
    ServerAdmin email@mydomain.com
    DocumentRoot /var/www/laravel/server.mydomain.com/public

    <Directory /var/www/laravel/server.mydomain.com>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/laravel-server.mydomain.com.error.log
    CustomLog ${APACHE_LOG_DIR}/laravel-server.mydomain.com.access.log combined
</VirtualHost>
```

So it seems not to be a PHP 8 issue.
In Laravel we have the basic auth package as well as the Voyager.

My composer.json

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.2",
        "spatie/laravel-activitylog": "^3.17",
        "tcg/voyager": "^1.4",
        "the42coders/workflows": "^0.0.4@beta"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "repositories": {
        "hooks": {
            "type": "composer",
            "url": "https://larapack.io"
        }
    }
}
```

**Comment by hobbycodersince1990** [comment]
Debugmode of Chrome says (in the headers tab of the Network tab):
```
Request URL: http://server.mydomain.com/workflows/settings/2/getElementSettings
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 62.171.185.116:80
Referrer Policy: strict-origin-when-cross-origin
Cache-Control: no-cache, private
Connection: close
Content-Type: text/html; charset=UTF-8
Date: Sat, 20 Mar 2021 08:52:52 GMT
Server: Apache/2.4.41 (Ubuntu)
Set-Cookie: XSRF-TOKEN=eyJpdiI6IkJST2hKbExuaFpHcU5kQno1N0Q2V0E9PSIsInZhbHVlIjoiYXo1WFZFRkR2NGpyMGNFSEZqRXdRU3pSajVVeUlvcEExVVpJdi95SkFmamNBNnFBUWJlYjhPdU9QcW5BYnVoNWxxSGx1dzlhUFVTZ3U5WlZqZ2JMM042SXFwV3JBY2UyNFdlMmtXK1ZUc0Y1R1RTTDBVblJhVUk4ZUcvKzlleXciLCJtYWMiOiIyZjczODNjODcyOTk5ZDEzNTUxMmFkNjU4NTk3MzgyYWJkMmQ4MzJjZWM0YWU2NDliYzZjNmEwOWYyYTIxMGMyIn0%3D; expires=Sat, 20-Mar-2021 10:52:52 GMT; Max-Age=7200; path=/; samesite=lax
Set-Cookie: server_session=eyJpdiI6IlQxRjZITkpBM1VIS21lZHE2V01taGc9PSIsInZhbHVlIjoiMTBBMTE0Y1YyeTIxeFp0a245S2plSXZtOURKcmZJS0JsK0I4VWNyUkp6dVNDc24xdkpPZHEzSzA2VklvQ2JGMEdHWERSWi9rVGpybWFhRmErbHgxd3gvaUt3QUFzZmIya0FMRzNqUkJjRjJyelo2Njh2TVBmMzROSW80NVJES0ciLCJtYWMiOiI4YzNhMDRlNTk1ODAyNjYwYjFlODBlODg0OWNjNzgwZjQ3MjBhM2NkZjE0MDJlN2I2MzcyOTU2ZTU5MDIzMGQzIn0%3D; expires=Sat, 20-Mar-2021 10:52:52 GMT; Max-Age=7200; path=/; httponly; samesite=lax
Transfer-Encoding: chunked
Accept: text/plain, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: en
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 22
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: _ga=GA1.2.1820927730.1600711618; __tawkuuid=e::mydomain.com::JZseVevUXzXS8zyXWDh6XbAZsB3EvoC70KzJ1Ed+OexJ21j/poJ0xHFTP6FRFYRH::2; hubspotutk=0549a4af2c1e45b3dd51be43dfda553c; __hssrc=1; __hs_opt_out=no; __hstc=139034924.0549a4af2c1e45b3dd51be43dfda553c.1600764345826.1607955270734.1608281410317.7; session=eyJuZXh0X3VybCI6Imh0dHA6Ly9zZXJ2ZXI4LmRldmxhYnMuYXQ6ODA4MC9jZHIvY29udGVudC8ifQ.YETagw.uI7of_ZfR2VDIjD4U25YIxdyTTw; PHPSESSID=l6qclhb67eh6j4u3h5ei58tfl2; _gid=GA1.2.1783769844.1616142522; XSRF-TOKEN=eyJpdiI6IndEOEpKUGpWSnpQOGkyUkhQS3R1RlE9PSIsInZhbHVlIjoiSDhwcGRPbVRmNzVhWlNIeVBGMHM3Q3B0cVpWZW45SnpMeUNBN05sZ2c5eW13MmpDcExaMUJRcDFNeDZ3SGI4Sy9JS2h6dFlobGwrUzZyeEdiYVk5V0p0cWMwSTdycEdnVENGcGxIS2lLRlBaWEhEbjlidkxBejJOQ0FNd1hOUEYiLCJtYWMiOiIzODg3Yjg3ZmQ4MjRmMGNjZWFmNDZkZTA5ZmFiYWVjMzRiZTk2NzM0N2Y2NzhhMTBkYmFmZjkwYWMxMjU0ZDFhIn0%3D; server_session=eyJpdiI6Imc3Rzd1R3RsZmhoQXVoUW9vTVFWTGc9PSIsInZhbHVlIjoiZlJNYWRCdVVBaWMvVnlkNWliSkh1Yklna0xMZCs5b2dkWEtzZkt3Um9Hc0NjMEwwMWRoaGdoV2FHT2JKSGYzMkFSMmErMTl2dHJLSDNFdTVZSVUyK3NnUjFqei9WMTZwS1N4Sk53WUh2WWZTTUp3dXBWc2cwTStaNFBFOUlmYlIiLCJtYWMiOiJlN2E3Y2U0MzZkNjQwNzBiZTJlZWQzNjA4Yjg2OTNlZDg5ZmEwMzFjMzNhMzM2ZTY0ZGY5ODlkOTY5OTNkMTY1In0%3D
Host: server.mydomain.com
Origin: http://server.mydomain.com
Pragma: no-cache
Referer: http://server.mydomain.com/workflows/2
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
X-CSRF-TOKEN: bWgi2cQdko6BLbC0C2Nlv11HQ1gAOYuymdWyiACJ
X-Requested-With: XMLHttpRequest
type: task
element_id: 2

```

And the Preview:

```
Facade\Ignition\Exceptions\ViewException: Class 'App\User' not found (View: /var/www/laravel/server.mydomain.com/resources/views/vendor/workflows/layouts/settings_overlay.blade.php) in file /var/www/laravel/server.mydomain.com/vendor/the42coders/workflows/src/DataBuses/ModelResource.php on line 26

#0 /var/www/laravel/server.mydomain.com/vendor/the42coders/workflows/src/Fields/TrixInputField.php(30): the42coders\Workflows\DataBuses\ModelResource::getValues()
#1 /var/www/laravel/server.mydomain.com/vendor/the42coders/workflows/src/DataBuses/ValueResource.php(34): the42coders\Workflows\Fields\TrixInputField->render()
#2 /var/www/laravel/server.mydomain.com/vendor/the42coders/workflows/src/Fields/Fieldable.php(83): the42coders\Workflows\DataBuses\ValueResource::loadResourceIntelligence()
#3 /var/www/laravel/server.mydomain.com/resources/views/vendor/workflows/layouts/settings_overlay.blade.php(30): the42coders\Workflows\Tasks\Task->loadResourceIntelligence()
#4 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/var/www/larave...')
#5 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#6 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#7 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#8 /var/www/laravel/server.mydomain.com/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\View\Engines\CompilerEngine->get()
#9 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\Ignition\Views\Engines\CompilerEngine->get()
#10 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View->getContents()
#11 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#12 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Http/Response.php(62): Illuminate\View\View->render()
#13 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Http/Response.php(34): Illuminate\Http\Response->setContent()
#14 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(789): Illuminate\Http\Response->__construct()
#15 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(759): Illuminate\Routing\Router::toResponse()
#16 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Routing\Router->prepareResponse()
#17 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#20 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle()
#22 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#24 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#26 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#28 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#29 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#31 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#33 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Pipeline\Pipeline->then()
#35 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack()
#36 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRoute()
#37 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->dispatchToRoute()
#38 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch()
#39 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#40 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#42 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#44 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#46 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#48 /var/www/laravel/server.mydomain.com/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#50 /var/www/laravel/server.mydomain.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#52 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then()
#54 /var/www/laravel/server.mydomain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#55 /var/www/laravel/server.mydomain.com/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#56 {main}


```

**Comment by hobbycodersince1990** [comment]
Seems to be an issue with the User class.

**Comment by Max-Hutschenreiter** [comment]
In the default, config is the User-defined as App\User since this changes now to be App\Models\User you need to publish the config and adapt it to your User model.

**Comment by hobbycodersince1990** [comment]
Thanks. This helped!
